# Default values for dual-bgp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Full bgpAdvertisement.spec supported except for ipAddressPools and ipAddressPoolSelectors.
# https://metallb.io/apis/#bgpadvertisementspec
# ipAddressPools should be defined using the top-level ipAddressPools list.
# ipAddressPoolSelectors spec not used as all pools should be advertised.
bgpAdvertisementSpec: {}

# Three values required at a minimum for a working BGPPeer resource.
bgpPeer1:
  myASN: null
  peerASN: null
  peerAddress: null

  # Optional: plaintext password (Helm turns this into a Secret)
  password: ""

  # Optional: name of an existing Secret in the namespace
  # Useful if you want to define a BGP password secret outside of this chart.
  existingPasswordSecret: ""

  # Optional extra BGPPeer spec.
  # Full BGPPeer spec supported: https://metallb.io/apis/#bgppeerspec
  # For example:
  # extraOptions:
  #   holdTime: "120s"
  #   keepaliveTime: "30s"
  extraOptions: {}

# Values of 'myASN', 'peerASN' and 'peerAddress' meets minimum spec for a working BGPPeer resource.
bgpPeer2:
  myASN: null
  peerASN: null
  peerAddress: null

  # Optional: plaintext password (Helm turns this into a Secret)
  password: ""

  # Optional: name of an existing Secret in the namespace
  # Useful if you want to define a BGP password secret outside of this chart.
  existingPasswordSecret: ""

  # Optional extra BGPPeer spec.
  # Full BGPPeer spec supported: https://metallb.io/apis/#bgppeerspec
  # For example:
  # extraOptions:
  #   holdTime: "120s"
  #   keepaliveTime: "30s"
  extraOptions: {}

ipAddressPools: []
  # - name: pool-1
  #   addresses:
  #     - 192.168.1.10/32
  #     - 92.168.1.20-192.168.1.30
  #   avoidBuggyIPs: true
  # - name: pool-2
  #   addresses:
  #     - 192.168.2.0/24
  #     - 192.168.3.0/24
  #   autoAssign: false