{{- if .Values.ipAddressPools }}
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ include "common.fullname" $ }}-advertisement
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "common.labels" $ | nindent 4 }}
spec:
  ipAddressPools:
    {{- range .Values.ipAddressPools }}
    - {{ .name }}
    {{- end }}
{{- end }}