apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ include "common.fullname" $ }}-peer1
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  myASN: {{ required "A valid bgpPeer1.myASN is required!" .Values.bgpPeer1.myASN }}
  peerASN: {{ required "A valid bgpPeer1.peerASN is required!" .Values.bgpPeer1.peerASN }}
  peerAddress: {{ required "A valid bgpPeer1.peerAddress is required!" .Values.bgpPeer1.peerAddress }}
  {{- if .Values.bgpPeer1.extraOptions }}
    {{- toYaml .Values.bgpPeer1.extraOptions | nindent 2 }}
  {{- end }}
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ include "common.fullname" $ }}-peer2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  myASN: {{ required "A valid bgpPeer2.myASN is required!" .Values.bgpPeer2.myASN }}
  peerASN: {{ required "A valid bgpPeer2.peerASN is required!" .Values.bgpPeer2.peerASN }}
  peerAddress: {{ required "A valid bgpPeer2.peerAddress is required!" .Values.bgpPeer2.peerAddress }}
  {{- if .Values.bgpPeer2.extraOptions }}
    {{- toYaml .Values.bgpPeer2.extraOptions | nindent 2 }}
  {{- end }}