apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ include "common.fullname" $ }}-dcgw1
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "common.labels" $ | nindent 4 }}
spec:
  myASN: {{ .Values.dcgw1.localASN }}
  peerAddress: {{ .Values.dcgw1.ipAddress }}
  peerASN: {{ .Values.dcgw1.remoteASN }}
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ include "common.fullname" $ }}-dcgw2
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "common.labels" $ | nindent 4 }}
spec:
  myASN: {{ .Values.dcgw2.localASN }}
  peerAddress: {{ .Values.dcgw2.ipAddress }}
  peerASN: {{ .Values.dcgw2.remoteASN }}