{{- if and .Values.bgpPeer1.password (not .Values.bgpPeer1.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" $ }}-peer1-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.bgpPeer1.password | quote }}
{{- end }}
---
{{- if and .Values.bgpPeer2.password (not .Values.bgpPeer2.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" $ }}-peer2-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.bgpPeer2.password | quote }}
{{- end }}